# Generated by Django 5.1 on 2025-01-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_specialization_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.ManyToManyField(to='doctor.designation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(to='doctor.specialization'),
        ),
    ]
